import type { Metadata } from 'next';
import './globals.css';
import Script from 'next/script';
export const metadata: Metadata = {
    title: 'My New App',
    description: 'Generated by Onlook',
};
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" data-oid="wa9gn.3">
            <body className="" data-oid="jla4qp_">
                {children}

                <Script src="/builtwith.js" strategy="afterInteractive" data-oid="dc62tjx" />
            </body>
        </html>
    );
}
